// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthorized() {
  return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email, and OAuth client id. Use to confirm the MCP connection is authenticated.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    return jsonResult({
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    });
  }
});

// src/lib/mcp/tools/list-my-clients.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_my_clients_default = defineTool2({
  name: "list_my_clients",
  title: "List my clients",
  description: "List AOS clients the signed-in user has access to. Admins see all clients; portal users see only clients linked to them via aos_client_users.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("aos_clients").select("id, full_name, company_name, industry, status, service_package, monthly_retainer, contract_start, contract_end").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, clients: data ?? [] });
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List AOS projects visible to the signed-in user. Optionally filter by client_id.",
  inputSchema: {
    client_id: z2.string().uuid().optional().describe("Filter to a specific client (UUID)."),
    status: z2.string().optional().describe("Filter by status (e.g. active, on_hold, completed)."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    let q = sb.from("aos_projects").select("id, name, description, status, priority, progress, start_date, end_date, client_id").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, projects: data ?? [] });
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_tasks_default = defineTool4({
  name: "list_tasks",
  title: "List tasks",
  description: "List AOS tasks visible to the signed-in user. Filter by project_id and/or status.",
  inputSchema: {
    project_id: z3.string().uuid().optional(),
    status: z3.string().optional().describe("e.g. todo, in_progress, review, done"),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    let q = sb.from("aos_tasks").select("id, title, description, status, priority, due_date, project_id, assignee_id").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (project_id) q = q.eq("project_id", project_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, tasks: data ?? [] });
  }
});

// src/lib/mcp/tools/list-approvals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_approvals_default = defineTool5({
  name: "list_approvals",
  title: "List approvals",
  description: "List AOS approval items visible to the signed-in user. Optionally filter by client_id or status.",
  inputSchema: {
    client_id: z4.string().uuid().optional(),
    status: z4.string().optional().describe("e.g. pending, approved, rejected"),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    let q = sb.from("aos_approvals").select("id, title, category, status, due_date, client_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (client_id) q = q.eq("client_id", client_id);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return jsonResult({ count: data?.length ?? 0, approvals: data ?? [] });
  }
});

// src/lib/mcp/tools/create-contact-lead.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^4.4.3";
var create_contact_lead_default = defineTool6({
  name: "create_contact_lead",
  title: "Create contact lead",
  description: "Create a new contact/enquiry lead in the CRM. Use when an assistant is capturing a lead on behalf of the signed-in user.",
  inputSchema: {
    name: z5.string().min(1).max(200),
    email: z5.string().email().max(255),
    phone: z5.string().max(40).optional(),
    message: z5.string().max(4e3).optional(),
    source: z5.string().max(60).optional().describe("Where the lead came from, e.g. 'mcp', 'chatgpt'. Defaults to 'mcp'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, email, phone, message, source }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthorized();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("contact_leads").insert({ name, email, phone: phone ?? null, message: message ?? null, source: source ?? "mcp" }).select("id, name, email, source, created_at").single();
    if (error) return errorResult(error.message);
    return jsonResult({ lead: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "drcpvdejjwnlxahqzgda";
var mcp_default = defineMcp({
  name: "am-enterprises-mcp",
  title: "AM Enterprises MCP",
  version: "0.1.0",
  instructions: "Tools for AM Enterprises. Callers act as the signed-in app user; row-level security decides what each user can read or write. Use `whoami` to verify the connection, then `list_my_clients`, `list_projects`, `list_tasks`, and `list_approvals` to browse the Agency Operating System. Use `create_contact_lead` to log a new enquiry in the CRM.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_clients_default, list_projects_default, list_tasks_default, list_approvals_default, create_contact_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
